version: "3.8"
services:
    # PHP Service
    php:
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8000:8000
        depends_on:
            - database
#            - redis
#            - node

    # node service
#    node:
#        build:
#            context: .
#            target: node
#        ports:
#            - 5173:5173
#        volumes:
#            - .:/usr/src
#            - ./node_modules:/usr/src/node_modules
#        tty: true
            # - redis

    # node service
    node:
        build:
            context: .
            target: node
        ports:
            - 5173:5173
        volumes:
            - .:/usr/src
            - ./node_modules:/usr/src/node_modules
        tty: true
        depends_on:
            - php

    # Database Server
    database:
        image: mysql:8.0
        ports:
            - 3308:3306
        env_file: 
            - .env
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USERNAME=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
#            - MYSQL_ALLOW_EMPTY_PASSWORD=1

        volumes:
            - dbbdata:/var/lib/mysql

    # Redis Server
#    redis:
#        image: redis:alpine
#        command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
#        ports:
#            - 6379:6379
    # # Redis Server
    # redis:
    #     image: redis:alpine
    #     command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    #     ports:
    #         - 6379:6379

volumes:
    dbbdata:
